#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <unordered_map>
#include <string>
#include <Windows.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/euler_angles.hpp>
#include <glm/gtx/norm.hpp>

using namespace glm;

#define SE_WINDOW_WIDTH 1024
#define SE_WINDOW_HEIGHT 768

#define DEBUG_PRINTF(...) {char cad[512]; sprintf(cad, __VA_ARGS__);  OutputDebugStringA(cad);}
#define CONSOLE_PRINTF(...) printf(__VA_ARGS__);

#ifndef SE_DEBUG_MODE
#define SE_DEBUG_MODE 0
#endif

enum class RENDER_API {
	OPENGL,
	DX12,
	DX11,
};

enum class PixelFormat
{
    PIXEL_FORMAT_UNKNOWN = 0,
    PIXEL_FORMAT_R32G32B32A32_TYPELESS = 1,
    PIXEL_FORMAT_R32G32B32A32_FLOAT = 2,
    PIXEL_FORMAT_R32G32B32A32_UINT = 3,
    PIXEL_FORMAT_R32G32B32A32_SINT = 4,
    PIXEL_FORMAT_R32G32B32_TYPELESS = 5,
    PIXEL_FORMAT_R32G32B32_FLOAT = 6,
    PIXEL_FORMAT_R32G32B32_UINT = 7,
    PIXEL_FORMAT_R32G32B32_SINT = 8,
    PIXEL_FORMAT_R16G16B16A16_TYPELESS = 9,
    PIXEL_FORMAT_R16G16B16A16_FLOAT = 10,
    PIXEL_FORMAT_R16G16B16A16_UNORM = 11,
    PIXEL_FORMAT_R16G16B16A16_UINT = 12,
    PIXEL_FORMAT_R16G16B16A16_SNORM = 13,
    PIXEL_FORMAT_R16G16B16A16_SINT = 14,
    PIXEL_FORMAT_R32G32_TYPELESS = 15,
    PIXEL_FORMAT_R32G32_FLOAT = 16,
    PIXEL_FORMAT_R32G32_UINT = 17,
    PIXEL_FORMAT_R32G32_SINT = 18,
    PIXEL_FORMAT_R32G8X24_TYPELESS = 19,
    PIXEL_FORMAT_D32_FLOAT_S8X24_UINT = 20,
    PIXEL_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
    PIXEL_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
    PIXEL_FORMAT_R10G10B10A2_TYPELESS = 23,
    PIXEL_FORMAT_R10G10B10A2_UNORM = 24,
    PIXEL_FORMAT_R10G10B10A2_UINT = 25,
    PIXEL_FORMAT_R11G11B10_FLOAT = 26,
    PIXEL_FORMAT_R8G8B8A8_TYPELESS = 27,
    PIXEL_FORMAT_R8G8B8A8_UNORM = 28,
    PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
    PIXEL_FORMAT_R8G8B8A8_UINT = 30,
    PIXEL_FORMAT_R8G8B8A8_SNORM = 31,
    PIXEL_FORMAT_R8G8B8A8_SINT = 32,
    PIXEL_FORMAT_R16G16_TYPELESS = 33,
    PIXEL_FORMAT_R16G16_FLOAT = 34,
    PIXEL_FORMAT_R16G16_UNORM = 35,
    PIXEL_FORMAT_R16G16_UINT = 36,
    PIXEL_FORMAT_R16G16_SNORM = 37,
    PIXEL_FORMAT_R16G16_SINT = 38,
    PIXEL_FORMAT_R32_TYPELESS = 39,
    PIXEL_FORMAT_D32_FLOAT = 40,
    PIXEL_FORMAT_R32_FLOAT = 41,
    PIXEL_FORMAT_R32_UINT = 42,
    PIXEL_FORMAT_R32_SINT = 43,
    PIXEL_FORMAT_R24G8_TYPELESS = 44,
    PIXEL_FORMAT_D24_UNORM_S8_UINT = 45,
    PIXEL_FORMAT_R24_UNORM_X8_TYPELESS = 46,
    PIXEL_FORMAT_X24_TYPELESS_G8_UINT = 47,
    PIXEL_FORMAT_R8G8_TYPELESS = 48,
    PIXEL_FORMAT_R8G8_UNORM = 49,
    PIXEL_FORMAT_R8G8_UINT = 50,
    PIXEL_FORMAT_R8G8_SNORM = 51,
    PIXEL_FORMAT_R8G8_SINT = 52,
    PIXEL_FORMAT_R16_TYPELESS = 53,
    PIXEL_FORMAT_R16_FLOAT = 54,
    PIXEL_FORMAT_D16_UNORM = 55,
    PIXEL_FORMAT_R16_UNORM = 56,
    PIXEL_FORMAT_R16_UINT = 57,
    PIXEL_FORMAT_R16_SNORM = 58,
    PIXEL_FORMAT_R16_SINT = 59,
    PIXEL_FORMAT_R8_TYPELESS = 60,
    PIXEL_FORMAT_R8_UNORM = 61,
    PIXEL_FORMAT_R8_UINT = 62,
    PIXEL_FORMAT_R8_SNORM = 63,
    PIXEL_FORMAT_R8_SINT = 64,
    PIXEL_FORMAT_A8_UNORM = 65,
    PIXEL_FORMAT_R1_UNORM = 66,
    PIXEL_FORMAT_R9G9B9E5_SHAREDEXP = 67,
    PIXEL_FORMAT_R8G8_B8G8_UNORM = 68,
    PIXEL_FORMAT_G8R8_G8B8_UNORM = 69,
    PIXEL_FORMAT_BC1_TYPELESS = 70,
    PIXEL_FORMAT_BC1_UNORM = 71,
    PIXEL_FORMAT_BC1_UNORM_SRGB = 72,
    PIXEL_FORMAT_BC2_TYPELESS = 73,
    PIXEL_FORMAT_BC2_UNORM = 74,
    PIXEL_FORMAT_BC2_UNORM_SRGB = 75,
    PIXEL_FORMAT_BC3_TYPELESS = 76,
    PIXEL_FORMAT_BC3_UNORM = 77,
    PIXEL_FORMAT_BC3_UNORM_SRGB = 78,
    PIXEL_FORMAT_BC4_TYPELESS = 79,
    PIXEL_FORMAT_BC4_UNORM = 80,
    PIXEL_FORMAT_BC4_SNORM = 81,
    PIXEL_FORMAT_BC5_TYPELESS = 82,
    PIXEL_FORMAT_BC5_UNORM = 83,
    PIXEL_FORMAT_BC5_SNORM = 84,
    PIXEL_FORMAT_B5G6R5_UNORM = 85,
    PIXEL_FORMAT_B5G5R5A1_UNORM = 86,
    PIXEL_FORMAT_B8G8R8A8_UNORM = 87,
    PIXEL_FORMAT_B8G8R8X8_UNORM = 88,
    PIXEL_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
    PIXEL_FORMAT_B8G8R8A8_TYPELESS = 90,
    PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
    PIXEL_FORMAT_B8G8R8X8_TYPELESS = 92,
    PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
    PIXEL_FORMAT_BC6H_TYPELESS = 94,
    PIXEL_FORMAT_BC6H_UF16 = 95,
    PIXEL_FORMAT_BC6H_SF16 = 96,
    PIXEL_FORMAT_BC7_TYPELESS = 97,
    PIXEL_FORMAT_BC7_UNORM = 98,
    PIXEL_FORMAT_BC7_UNORM_SRGB = 99,
    PIXEL_FORMAT_AYUV = 100,
    PIXEL_FORMAT_Y410 = 101,
    PIXEL_FORMAT_Y416 = 102,
    PIXEL_FORMAT_NV12 = 103,
    PIXEL_FORMAT_P010 = 104,
    PIXEL_FORMAT_P016 = 105,
    PIXEL_FORMAT_420_OPAQUE = 106,
    PIXEL_FORMAT_YUY2 = 107,
    PIXEL_FORMAT_Y210 = 108,
    PIXEL_FORMAT_Y216 = 109,
    PIXEL_FORMAT_NV11 = 110,
    PIXEL_FORMAT_AI44 = 111,
    PIXEL_FORMAT_IA44 = 112,
    PIXEL_FORMAT_P8 = 113,
    PIXEL_FORMAT_A8P8 = 114,
    PIXEL_FORMAT_B4G4R4A4_UNORM = 115,

    PIXEL_FORMAT_P208 = 130,
    PIXEL_FORMAT_V208 = 131,
    PIXEL_FORMAT_V408 = 132,

    PIXEL_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE = 189,
    PIXEL_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE = 190,

};

static std::unordered_map<PixelFormat, const char*> PixelFormatStr
{
    {PixelFormat::PIXEL_FORMAT_UNKNOWN, "UNKNOWN"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32A32_TYPELESS, "R32G32B32A32_TYPELESS"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32A32_FLOAT, "R32G32B32A32_FLOAT"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32A32_UINT, "R32G32B32A32_UINT"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32A32_SINT, "R32G32B32A32_SINT"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32_TYPELESS, "R32G32B32_TYPELESS"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32_FLOAT, "R32G32B32_FLOAT"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32_UINT, "R32G32B32_UINT"},
    {PixelFormat::PIXEL_FORMAT_R32G32B32_SINT, "R32G32B32_SINT"},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_TYPELESS, "R16G16B16A16_TYPELESS"},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_FLOAT, "R16G16B16A16_FLOAT"},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_UNORM, "R16G16B16A16_UNORM"},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_UINT, "R16G16B16A16_UINT"},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16B16A16_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32G32_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R32G32_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_R32G32_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32G32_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32G8X24_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_D32_FLOAT_S8X24_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32_FLOAT_X8X24_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_X32_TYPELESS_G8X24_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R10G10B10A2_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R10G10B10A2_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R10G10B10A2_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R11G11B10_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_TYPELESS, "R8G8B8A8_TYPELESS"},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_UNORM, "R8G8B8A8_UNORM"},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB, "R8G8B8A8_UNORM_SRGB"},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_UINT, "R8G8B8A8_UINT"},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_SNORM, "R8G8B8A8_SNORM"},
    {PixelFormat::PIXEL_FORMAT_R8G8B8A8_SINT, "R8G8B8A8_SINT"},
    {PixelFormat::PIXEL_FORMAT_R16G16_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16G16_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_D32_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_R32_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_R32_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R32_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R24G8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_D24_UNORM_S8_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R24_UNORM_X8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_X24_TYPELESS_G8_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R16_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R16_FLOAT, ""},
    {PixelFormat::PIXEL_FORMAT_D16_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R16_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R16_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_R8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_R8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R8_UINT, ""},
    {PixelFormat::PIXEL_FORMAT_R8_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R8_SINT, ""},
    {PixelFormat::PIXEL_FORMAT_A8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R1_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R9G9B9E5_SHAREDEXP, ""},
    {PixelFormat::PIXEL_FORMAT_R8G8_B8G8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_G8R8_G8B8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC1_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC1_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC1_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_BC2_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC2_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC2_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_BC3_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC3_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC3_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_BC4_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC4_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC4_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC5_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC5_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC5_SNORM, ""},
    {PixelFormat::PIXEL_FORMAT_B5G6R5_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_B5G5R5A1_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8A8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8X8_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8A8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8X8_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_BC6H_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC6H_UF16, ""},
    {PixelFormat::PIXEL_FORMAT_BC6H_SF16, ""},
    {PixelFormat::PIXEL_FORMAT_BC7_TYPELESS, ""},
    {PixelFormat::PIXEL_FORMAT_BC7_UNORM, ""},
    {PixelFormat::PIXEL_FORMAT_BC7_UNORM_SRGB, ""},
    {PixelFormat::PIXEL_FORMAT_AYUV, ""},
    {PixelFormat::PIXEL_FORMAT_Y410, ""},
    {PixelFormat::PIXEL_FORMAT_Y416, ""},
    {PixelFormat::PIXEL_FORMAT_NV12, ""},
    {PixelFormat::PIXEL_FORMAT_P010, ""},
    {PixelFormat::PIXEL_FORMAT_P016, ""},
    {PixelFormat::PIXEL_FORMAT_420_OPAQUE, ""},
    {PixelFormat::PIXEL_FORMAT_YUY2, ""},
    {PixelFormat::PIXEL_FORMAT_Y210, ""},
    {PixelFormat::PIXEL_FORMAT_Y216, ""},
    {PixelFormat::PIXEL_FORMAT_NV11, ""},
    {PixelFormat::PIXEL_FORMAT_AI44, ""},
    {PixelFormat::PIXEL_FORMAT_IA44, ""},
    {PixelFormat::PIXEL_FORMAT_P8, ""},
    {PixelFormat::PIXEL_FORMAT_A8P8, ""},
    {PixelFormat::PIXEL_FORMAT_B4G4R4A4_UNORM, ""},

    {PixelFormat::PIXEL_FORMAT_P208, ""},
    {PixelFormat::PIXEL_FORMAT_V208, ""},
    {PixelFormat::PIXEL_FORMAT_V408, ""},

    {PixelFormat::PIXEL_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE, ""},
    {PixelFormat::PIXEL_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE, ""},

};

struct VertexLayoutDesc 
{

};


struct TextureDesc
{

};

struct BufferDesc
{

};


enum class CommonKeyCode {
	A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
	ESCAPE,LEFT_MOUSE, RIGHT_MOUSE, MIDDLE_MOUSE, LEFT_ARROW,
	RIGHT_ARROW, UP_ARROW, DOWN_ARROW, LEFT_SHIFT,
};

enum class CommonKeyState
{
	NONE, 
	PRESSED,
	RELEASED,
	REPEATED,
};
